### ISSUE TITLE
Richiesta dati raw o chiarimento su normalizzazione

### ISSUE THREAD

**Issue by opencovid-mr** [Scienzainrete/covid-19#1]
Sarebbe possibile avere i dati raw dei nuovi casi per settimana di diagnosi delle 11 regioni monitorate?

In alternativa sarebbe possibile sapere se le normalizzazioni per calcolare l'incidenza per settimana e per classe di età sono state fatte in base (ad esempio) alla popolazione residente al 1 gennaio 2020 come da dati ISTAT?

http://demo.istat.it/popres/index.php?anno=2020&lingua=ita

Un ringraziamento in anticipo.

**Comment by sergiocima** [comment]
Grazie, giriamo all'AIE la richiesta.

**Comment by sergiocima** [comment]
Non possiamo dare i dati RAW perché non c'è un accordo in tal senso con le Regioni. Ti confermo invece che è stata usata la popolazione residente al 1 gennaio 2020.

**Comment by opencovid-mr** [comment]
Perfetto, si procederà con la "de-normalizzazione" a partire dai dati ISTAT. Grazie della disponibilità e complimenti per il lavoro.
